version: '3.8'

services:
  comnica:
    container_name: comnica
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3105:3001
